### ISSUE TITLE
どうやってインストールができる？

### ISSUE THREAD

**Issue by vuvanly** [ksoichiro/gitlab-i18n-patch#10]
説明内容をなんでも確認しましたが、インストール方法がさっぱりわからないです。
お手数をかけますが、教えていただけないでしょうか？

**Comment by ksoichiro** [comment]
@vuvanly 

インストール方法は
READMEに「適用方法」として書いているもので、
#9にてお試しいただいていた方法で合っていると思われます。
どのようなエラーに遭遇されたのでしょうか？
GitLabとパッチのバージョンは一致していますか？

**Comment by vuvanly** [comment]
すみません、
以下のインストール手順でできました。
```sh
wget https://raw.githubusercontent.com/ksoichiro/gitlab-i18n-patch/master/patches/v8.16.6/app_ja.patch
cd /opt/gitlab/embedded/service/gitlab-rails
sudo patch -p1 < ~/app_ja.patch 
```
でもやはりGitlabは多言語の切り替えができないですね。うちのチームは日本人とベトナム人がいますから。

**Comment by ksoichiro** [comment]
解決して良かったです。
#9 で試されていたものは raw のファイルではなかったということですね。
README を修正しておきます。

> でもやはりGitlabは多言語の切り替えができないですね。

これは難しそうです…。GitLab本体側での対応を期待したいですね。
