### ISSUE TITLE
GitLab本体へのマージは？

### ISSUE THREAD

**Issue by hkato** [ksoichiro/gitlab-i18n-patch#12]
国際化が投入されたものがついにリリースされましたね。
翻訳リソースを本体にマージされる予定はありますか？

https://about.gitlab.com/2017/05/22/gitlab-9-2-released/
https://gitlab.com/gitlab-org/gitlab-ce/issues/4012

**Comment by hkato** [comment]
翻訳を次のURLで実施しています。

- Zanata : GitLab
    - https://translate.zanata.org/project/view/GitLab
- Slack : gitlab-jp#translation
    - https://gitlab-jp.slack.com/messages/C5N6F5L2E

**Comment by tnir** [comment]
FYI: 2017年8月に翻訳サイトはZanataからCrowdinへ移行となりました。

- Crowdin : GitLab
  - http://translate.gitlab.com/translate/gitlab-ee/6/en-ja

**Comment by ksoichiro** [comment]
長らく返答できておらず申し訳ありませんでした。

[このリポジトリを紹介したQiitaの投稿](https://qiita.com/ksoichiro/items/f63196aa0a7f07c1862d)にて翻訳について教えていただき、このリポジトリの翻訳も使っていただけるなら使ってくださいとお伝えしました。

それから大分経ち、実際に翻訳は進んでいるようですが、まだ完全には翻訳されておらず設定画面の説明でも experimental と説明されているようですね。

このリポジトリのパッチを使っているブログ記事もちらほら見かけまして、まだもう少しの間はこのリポジトリのパッチも有用なケースがありそうに思いましたので、もうしばらくの間、メンテナンスさせていただこうと思います。
