### ISSUE TITLE
GitLab 8.9.4の対応していますか？

### ISSUE THREAD

**Issue by msaus** [ksoichiro/gitlab-i18n-patch#13]
Patchを確認した所v8.9.6のpatchしかなかったので、これを8.9.4にいれられますか？
以上、宜しくお願い致します。

**Comment by ksoichiro** [comment]
遅くなりすみません。v8.9.4を追加させていただきました。
(もう不要かもしれませんが...)

**Comment by msaus** [comment]
ご対応有難うございます。大変助かりました。
