### ISSUE TITLE
GITLAB_VERSION

### ISSUE THREAD

**Issue by nobuakiy** [ksoichiro/gitlab-i18n-patch#2]
v830をvagrantで動かしてみました。
ちょっと修正が必要でしたので、お知らせします。
GITLAB_VERSIONの最初の"v"を削除しないと動かない部分がありました。
たぶん、pushを忘れているのだと思います。
パッチする部分は、手動で動かしました。

当面、個人的に使って、次回のプロジェクトからは、
全面的に採用したいと思います。
やっぱり、英語だと受け付けてもらえないので。。。
開発の継続をおねがいします。
なにかお手伝いできることがあれば、教えてください。

diff --git a/lib/provision.sh b/lib/provision.sh
index 62c1cf5..d60dfec 100755
--- a/lib/provision.sh
+++ b/lib/provision.sh
@@ -2,7 +2,7 @@

 VAGRANT_SYNC_DIR=/vagrant
 GITLAB_INSTALLER_DIR=packages
-GITLAB_VERSION=$1
+GITLAB_VERSION=`echo -n "$1" | sed -e "s/^v//g"`
 GITLAB_VERSION_INT=`echo -n "${GITLAB_VERSION}" | sed -e "s/\.//g"`
 GITLAB_WEB_PORT=$2
 GITLAB_INSTALLER_URL=$3

**Comment by ksoichiro** [comment]
フィードバックありがとうございます！
パッチ作成の方式を変えてからVagrantでの確認はしばらくできていなかったので
いただいた diff を参考に修正します。

> 当面、個人的に使って、次回のプロジェクトからは、
> 全面的に採用したいと思います。
> やっぱり、英語だと受け付けてもらえないので。。。
> 開発の継続をおねがいします。

採用を検討いただいているとのこと、ありがとうございます。
継続しますので、ご要望などあればご連絡いただければと思います。

**Comment by ksoichiro** [comment]
解決していると思いますので、クローズさせていただきます。
