### ISSUE TITLE
Template Error

### ISSUE THREAD

**Issue by lunch2000** [ksoichiro/gitlab-i18n-patch#3]
翻訳パッチの作成ありがとうございます。
大変助かっています。

パッチを適用したところ、500エラーが発生するようになってしまいました。
GitLabのバージョンは8.10.5です。
以下、production.logの内容です。

Started GET "/○○○/▲▲▲" for 1.33.204.82 at 2016-08-15 09:58:08 +0900
Processing by ProjectsController#show as HTML
Parameters: {"namespace_id"=>"○○○", "id"=>"▲▲▲"}
Read fragment views/○○○/▲▲▲-68a265876c85322b238a64eded4031fc1c3df433-readme/6e1c334cb4104b0dd5ff60f7784a9511 (0.3ms)
Completed 500 Internal Server Error in 1107ms (ActiveRecord: 57.2ms)
ActionView::Template::Error (undefined local variable or method `ラベル' for #<#<Class:0x00000012225df0>:0x00000012234fd0>):
7: = form_tag search_path, method: :get, class: 'navbar-form' do |f|
8: .search-input-container
9: - if label.present?
10: .location-badge= ラベル
11: .search-input-wrap
12: .dropdown{ data: {url: search_autocomplete_path } }
13: = search_field_tag "search", nil, placeholder: '検索', class: "search-input dropdown-menu-toggle", spellcheck: false, tabindex: "1", autocomplete: 'off', data: { toggle: 'dropdown' }
app/views/layouts/_search.html.haml:10:in`block in _app_views_layouts__search_html_haml__2460190743252752103_60737040'
app/views/layouts/_search.html.haml:7:in `_app_views_layouts__search_html_haml__2460190743252752103_60737040'
app/views/layouts/header/_default.html.haml:14:in`_app_views_layouts_header__default_html_haml___299695599040993552_127275600'
app/views/layouts/application.html.haml:10:in `_app_views_layouts_application_html_haml__2552820584669250243_145562880'
app/views/layouts/project.html.haml:28:in`_app_views_layouts_project_html_haml__118160325366461810_152168580'
app/controllers/projects_controller.rb:112:in `block (2 levels) in show'
app/controllers/projects_controller.rb:104:in`show'
lib/gitlab/middleware/go.rb:16:in `call'

**Comment by ksoichiro** [comment]
フィードバックありがとうございます！
修正できたと思いますので、ご確認いただければと思います。

**Comment by lunch2000** [comment]
問題が解消されていることを確認しました。
ご対応ありがとうございました。
