### ISSUE TITLE
GitLab kanban board

### ISSUE THREAD

**Issue by sunecosuri** [ksoichiro/gitlab-i18n-patch#4]
dockerで以下のDockfileからビルドして実行したのですが
カンバンボードが動きません。
引き続き、こちらでも調査してわかり次第共有させていただきます。

FROM sameersbn/gitlab:8.11.4
MAINTAINER sunecosuri
RUN apt-get update && apt-get -y install patch
RUN wget -O app_ja.patch https://raw.githubusercontent.com/ksoichiro/gitlab-i18n-patch/master/patches/v8.11.4/app_ja.patch && \
    patch -p1 < app_ja.patch && \
    rm app_ja.patch

**Comment by ksoichiro** [comment]
@sunecosuri フィードバックありがとうございます！
ボードに課題が表示されない、ということでよろしいでしょうか。
確認したところ日本語にしてはいけない部分まで日本語化してしまっていたようです。
修正しましたので、ご確認いただけますでしょうか。

**Comment by sunecosuri** [comment]
返信が遅れましてすみません。
確認したところ無事ボードが動きました！
またなにかありましたらissue挙げます。
この度は、ありがとうございました。

**Comment by ksoichiro** [comment]
ご確認ありがとうございました。動作して良かったです。
